services:
  db:
    image: postgres:15-alpine
    container_name: presensi_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      TZ: Asia/Jakarta
      PGTZ: Asia/Jakarta
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    container_name: presensi_web
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - TZ=Asia/Jakarta
    env_file:
      - .env # <-- Ini kunci rahasianya, biar otomatis ngebaca file .env server
    volumes:
      - ./dataset:/app/dataset
      - ./trainer:/app/trainer
      - ./encodings:/app/encodings
      - ./static:/app/static

volumes:
  pgdata:
